### ISSUE TITLE
Error Message: connect EACCES /var/run/docker.sock

### ISSUE THREAD

**Issue by baiyutang** [microsoft/vscode-docker#1193]
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: EACCES
Error Message: connect EACCES /var/run/docker.sock

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

----
`/var/run/`
```
srw-rw----  1 root              docker      0 8月   8 11:40 docker.sock
```

Is this reason that vscode is not in the group docker ?

**Comment by EricJizbaMSFT** [comment]
@baiyutang yeah make sure you follow the steps in “Manage Docker as a non-root user” from Post-installation steps for Linux for the extension to be able to access docker.

https://docs.docker.com/install/linux/linux-postinstall/

**Comment by baiyutang** [comment]
@EricJizbaMSFT  ok，I will read it,then have a try.Thant you.

**Comment by andreheringer** [comment]
Having the same issue. I've followed the steps in the linux post installation but the problem persisted. Tried to reinstall the extension but no luck. 

Also tired to reload the extension on a fresh installation of vscode 1.37 and the problem persisted.
Downloading and installing older version of the extension and no progress so far.

**Comment by StephenWeatherford** [comment]
Can you successfully run 'docker' on a Linux terminal?

**Comment by andreheringer** [comment]
I've updated my system and rebooted, and now it works. Does docker require a reboot so it can finish its installation?

Anyways, thank you guys for the attention.

**Comment by baiyutang** [comment]
> @baiyutang yeah make sure you follow the steps in “Manage Docker as a non-root user” from Post-installation steps for Linux for the extension to be able to access docker.
> 
> https://docs.docker.com/install/linux/linux-postinstall/

My problem is solved，Thank you.

**Comment by luozhouyang** [comment]
> Can you successfully run 'docker' on a Linux terminal?

I can run all the docker commands in terminal, but the problem persisted.

I have been using docker for months and every thing is ok. But I try the vs code remote container, the error message occurs: **connect EACCES /var/run/docker.sock**

![error_docker](https://user-images.githubusercontent.com/34032031/63831248-d5c63d80-c9a0-11e9-9926-b9c6adf173be.jpeg)

**Comment by baiyutang** [comment]
> > Can you successfully run 'docker' on a Linux terminal?
> 
> I can run all the docker commands in terminal, but the problem persisted.
> 
> I have been using docker for months and every thing is ok. But I try the vs code remote container, the error message occurs: **connect EACCES /var/run/docker.sock**
> 
> ![error_docker](https://user-images.githubusercontent.com/34032031/63831248-d5c63d80-c9a0-11e9-9926-b9c6adf173be.jpeg)

Did you have  a try like this ?

![image](https://user-images.githubusercontent.com/10782183/63831991-71a47900-c9a2-11e9-9ca9-77211e211322.png)

https://docs.docker.com/install/linux/linux-postinstall/
