### ISSUE TITLE
Build Image uses wrong path separator when default terminal is git bash on Windows

### ISSUE THREAD

**Issue by Szauka** [microsoft/vscode-docker#902]
Vs Code:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

Projet structure:

```
main
└───project
          └───sub_project
                        -Dockerfile
```

the run command is:
`$ docker build --rm -f "project\sub_project\Dockerfile" -t sub_project:latest project\sub_project`

Error:
`unable to prepare context: path "projectsub_project" not found`

![image](https://user-images.githubusercontent.com/33459309/56366422-02946800-61eb-11e9-8659-ad00980a9248.png)

**Comment by EricJizbaMSFT** [comment]
@Szauka Are you by chance running in WSL? Could be similar issue to https://github.com/microsoft/vscode-docker/issues/960

**Comment by EricJizbaMSFT** [comment]
I ask because your run command has `$` at the beginning instead of a more typical PowerShell or cmd prompt prefix

**Comment by Szauka** [comment]
> 
> 
> I ask because your run command has `$` at the beginning instead of a more typical PowerShell or cmd prompt prefix

@EricJizbaMSFT I'm not running in WSL. The reason that my command has `$` is because I have set Git Bash as the internal terminal for VS Code.

**Comment by EricJizbaMSFT** [comment]
@Szauka thanks for the info - we'll look into it

**Comment by bwateratmsft** [comment]
Potentially resolved by #1245

**Comment by Szauka** [comment]
> 
> 
> Potentially resolved by #1245

I can see that the merge of #1245 has generated the build:  `20190916.4`
I have tested the build: `20190918.1` and this issue is still happening

**Comment by bwateratmsft** [comment]
Can you run the command `Docker: Initialize for debugging...`? It will create a `docker-build` task in tasks.json. If that task exists, right click Dockerfile -> Build Image will execute the task; otherwise it uses the existing behavior.

**Comment by Szauka** [comment]
Hi @bwateratmsft running `Docker: Initialize for debugging...` works fine for both cases, running it from the context menu after selecting the Dockerfile and from the command palette.

**Comment by bwateratmsft** [comment]
Awesome! Glad to hear it!

**Comment by Szauka** [comment]
Is this change going to make it into the next release?

**Comment by bwateratmsft** [comment]
That's the plan.
